project_name: kubeprobes

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: kubeprobes
    main: ./cmd/kubeprobes
    binary: kubeprobes
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: Tech-Preta
    name: kubeprobes
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  - image_templates:
      - "ghcr.io/tech-preta/kubeprobes:{{ .Tag }}"
      - "ghcr.io/tech-preta/kubeprobes:v{{ .Major }}"
      - "ghcr.io/tech-preta/kubeprobes:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/tech-preta/kubeprobes:latest"
    dockerfile: Dockerfile
    build_contexts:
      kubeprobes: "{{ .Path }}"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Kubernetes health checks and probe analysis tool"
      - "--label=org.opencontainers.image.url=https://github.com/Tech-Preta/kubeprobes"
      - "--label=org.opencontainers.image.source=https://github.com/Tech-Preta/kubeprobes"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
