apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: secure-ns
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: my-app-container
      image: nginx:1.28.0
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
          ephemeral-storage: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
          ephemeral-storage: "256Mi"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10001
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      startupProbe:
        httpGet:
          path: /startup
          port: 8080
        failureThreshold: 30
        periodSeconds: 10
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  automountServiceAccountToken: false
  volumes:
    - name: tmp
      emptyDir: {}
