name: Code Review Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check for Code Review
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const hasApproval = reviews.some(review => review.state === 'APPROVED');

            if (!hasApproval) {
              console.log('Warning: No approval found. Proceeding anyway.');
            }
