name: Branch Protection Rules
description: Rules to protect the main branch
enforcement: active
target: branch
rules:
  - name: Require pull request reviews before merging
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: true
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require status checks to pass before merging
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - "Code Review Check"
          - "OSV-Scanner"
          - "Checkov Security Scan"
          - "Release"
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require branches to be up to date before merging
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require conversation resolution before merging
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require signed commits
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require linear history
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require deployments to succeed before merging
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Require merge queue
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Prevent force pushes
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

  - name: Prevent branch deletion
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: [] 